
perovskite_aliases = {
    'CsPbBrBrBr': str(1),
    'CsPbBrBrCl': str(2),
    'CsPbBrBrI': str(3),
    'CsPbBrClCl': str(4),
    'CsPbBrClI': str(5),
    'CsPbBrII': str(6),
    'CsPbClClCl': str(7),
    'CsPbClClI': str(8),
    'CsPbClII': str(9),
    'CsPbIII': str(10),
    'FAPbBrBrBr': str(11),
    'FAPbBrBrCl': str(12),
    'FAPbBrBrI': str(13),
    'FAPbBrClCl': str(14),
    'FAPbBrClI': str(15),
    'FAPbBrII': str(16),
    'FAPbClClCl': str(17),
    'FAPbClClI': str(18),
    'FAPbClII': str(19),
    'FAPbIII': str(20),
    'MAPbBrBrBr': str(21),
    'MAPbBrBrCl': str(22),
    'MAPbBrBrI': str(23),
    'MAPbBrClCl': str(24),
    'MAPbBrClI': str(25),
    'MAPbBrII': str(26),
    'MAPbClClCl': str(27),
    'MAPbClClI': str(28),
    'MAPbClII': str(29),
    'MAPbIII': str(30)
}
perovskite_aliases.update({v: k for k, v in perovskite_aliases.items()})
